### ISSUE TITLE
一使用就会闪退

### ISSUE THREAD

**Issue by BlackTitle** [Just-to-it/zhijiaoyun#4]
使用环境:腾讯云轻量服务器
然后我用Pychram运行了一遍发现了报错
`请选择刷视频速度:1.正常  2.二倍  3. 五倍  4.十倍  1
是否需要评论:1.需要  2.不需要  2
Traceback (most recent call last):
  File "C:\Users\27751\Downloads\zhijiaoyun-main\zhijiaoyun\main.py", line 530, in <module>
    getCookie_acw_tc()
  File "C:\Users\27751\Downloads\zhijiaoyun-main\zhijiaoyun\main.py", line 50, in getCookie_acw_tc
    session.get(url, verify=False)
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\27751\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname`

**Comment by Just-to-it** [comment]
我百度了一下， 应该是requests库版本高了, 我的 requests==2.23.0,&nbsp;urllib3==1.25.8。主要应该是requests库,python版本3.7.4(应该不是这个问题)。你改一下版本试试, 我今天跑了三个号, 都没问题。
随便提一嘴, 该程序报错基本都是JSON...开头什么的报错。这是因为我们在一直连续session.pot/get请求, 服务器返回了非正常数据对象,导致json解析失败(我也没异常处理)。(我在app试过, 一种很快的速度手动，手动发送评论),一段时间后会出现加载中的圆圈, 拿不到数据了。
程序遇到这种, 基本等个5-10分钟, 就可以再次运行了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Just-to-it/zhijiaoyun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月18日(星期二) 上午10:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Just-to-it/zhijiaoyun] 一使用就会闪退 (#4)





 
使用环境:腾讯云轻量服务器

**Comment by BlackTitle** [comment]
> 我百度了一下， 应该是requests库版本高了, 我的 requests==2.23.0,&nbsp;urllib3==1.25.8。主要应该是requests库,python版本3.7.4(应该不是这个问题)。你改一下版本试试, 我今天跑了三个号, 都没问题。 随便提一嘴, 该程序报错基本都是JSON...开头什么的报错。这是因为我们在一直连续session.pot/get请求, 服务器返回了非正常数据对象,导致json解析失败(我也没异常处理)。(我在app试过, 一种很快的速度手动，手动发送评论),一段时间后会出现加载中的圆圈, 拿不到数据了。 程序遇到这种, 基本等个5-10分钟, 就可以再次运行了。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Just-to-it/zhijiaoyun" ***@***.***&gt;; 发送时间:&nbsp;2021年5月18日(星期二) 上午10:21 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[Just-to-it/zhijiaoyun] 一使用就会闪退 (#4) 使用环境:腾讯云轻量服务器 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

方便给一下muggle_ocr的安装源和captcha的版本吗，我通过腾讯源安装了muggle-ocr，但是还是提示
`Traceback (most recent call last):
  File "C:\Users\27751\Downloads\zhijiaoyun-main\zhijiaoyun-main\main.py", line 8, in <module>
    from utils import captcha
  File "C:\Users\27751\Downloads\zhijiaoyun-main\zhijiaoyun-main\utils.py", line 1, in <module>
    import muggle_ocr
ModuleNotFoundError: No module named 'muggle_ocr'
`

**Comment by Just-to-it** [comment]
> > 我百度了一下， 应该是requests库版本高了, 我的 requests==2.23.0, urllib3==1.25.8。主要应该是requests库,python版本3.7.4(应该不是这个问题)。你改一下版本试试, 我今天跑了三个号, 都没问题。 随便提一嘴, 该程序报错基本都是JSON...开头什么的报错。这是因为我们在一直连续session.pot/get请求, 服务器返回了非正常数据对象,导致json解析失败(我也没异常处理)。(我在app试过, 一种很快的速度手动，手动发送评论),一段时间后会出现加载中的圆圈, 拿不到数据了。 程序遇到这种, 基本等个5-10分钟, 就可以再次运行了。
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Just-to-it/zhijiaoyun" _**@**_._**>; 发送时间: 2021年5月18日(星期二) 上午10:21 _**@**_.**_>; _**@**_.***>; 主题: [Just-to-it/zhijiaoyun] 一使用就会闪退 (#4) 使用环境:腾讯云轻量服务器 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 方便给一下muggle_ocr的安装源和captcha的版本吗，我通过腾讯源安装了muggle-ocr，但是还是提示
> `Traceback (most recent call last): File "C:\Users\27751\Downloads\zhijiaoyun-main\zhijiaoyun-main\main.py", line 8, in <module> from utils import captcha File "C:\Users\27751\Downloads\zhijiaoyun-main\zhijiaoyun-main\utils.py", line 1, in <module> import muggle_ocr ModuleNotFoundError: No module named 'muggle_ocr' `

READERME.md文件有安装源

**Comment by Just-to-it** [comment]
> > 我百度了一下， 应该是requests库版本高了, 我的 requests==2.23.0, urllib3==1.25.8。主要应该是requests库,python版本3.7.4(应该不是这个问题)。你改一下版本试试, 我今天跑了三个号, 都没问题。 随便提一嘴, 该程序报错基本都是JSON...开头什么的报错。这是因为我们在一直连续session.pot/get请求, 服务器返回了非正常数据对象,导致json解析失败(我也没异常处理)。(我在app试过, 一种很快的速度手动，手动发送评论),一段时间后会出现加载中的圆圈, 拿不到数据了。 程序遇到这种, 基本等个5-10分钟, 就可以再次运行了。
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Just-to-it/zhijiaoyun" _**@**_._**>; 发送时间: 2021年5月18日(星期二) 上午10:21 _**@**_.**_>; _**@**_.***>; 主题: [Just-to-it/zhijiaoyun] 一使用就会闪退 (#4) 使用环境:腾讯云轻量服务器 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 方便给一下muggle_ocr的安装源和captcha的版本吗，我通过腾讯源安装了muggle-ocr，但是还是提示
> `Traceback (most recent call last): File "C:\Users\27751\Downloads\zhijiaoyun-main\zhijiaoyun-main\main.py", line 8, in <module> from utils import captcha File "C:\Users\27751\Downloads\zhijiaoyun-main\zhijiaoyun-main\utils.py", line 1, in <module> import muggle_ocr ModuleNotFoundError: No module named 'muggle_ocr' `

READERME.md文件有安装源
