### ISSUE TITLE
使用一会儿，就开始报错，还有就是swf文件不能识别

### ISSUE THREAD

**Issue by Hawkenm** [Just-to-it/zhijiaoyun#5]
章节:项目四 蔬菜生产
     子目录:绿叶菜类蔬菜生产
           文件: 10绿叶菜栽培技术.., 进度100%(自动跳过)
     子目录:白菜类蔬菜生产
           文件: 08白菜类.., 进度100%(自动跳过)
     子目录:茄果类蔬菜生产
           文件: 10.茄子的植物学特.., 进度100%(自动跳过)
           文件: 11茄果类栽培技术.., 进度100%(自动跳过)
           文件: 6.番茄类型.., 进度100%(自动跳过)
           文件: 7.番茄的整枝方式.., 进度100%(自动跳过)
           文件: 8.番茄常见生理性病.., 进度100%(自动跳过)
           文件: 9.茄子的类型.., 进度100%(自动跳过)
           文件: 爱剪辑-茄子的整枝技.., 进度100%(自动跳过)
     子目录:瓜类蔬菜生产
           文件: 09瓜类蔬菜.., 进度100%(自动跳过)
     子目录:根菜类蔬菜生产
           文件: 根菜类蔬菜生产.., 进度100%(自动跳过)
     子目录:葱蒜类蔬菜生产
           文件: 葱蒜类蔬菜生产.., 进度100%(自动跳过)
     子目录:豆类蔬菜生产
           文件: 豆类蔬菜.., 进度100%(自动跳过)
Traceback (most recent call last):
  File "C:\Users\yaoyu\Desktop\zhijiaoyun-main\main.py", line 534, in <module>
    login(userName, passWord, sleepTime, needPinglun)
  File "C:\Users\yaoyu\Desktop\zhijiaoyun-main\main.py", line 86, in login
    choose_course(token, sleepTime, needPinglun)
  File "C:\Users\yaoyu\Desktop\zhijiaoyun-main\main.py", line 106, in choose_course
    chapterInfo(course, token, sleepTime, needPinglun)
  File "C:\Users\yaoyu\Desktop\zhijiaoyun-main\main.py", line 137, in chapterInfo
    topicInfo(listChapter, token, sleepTime, needPinglun)
  File "C:\Users\yaoyu\Desktop\zhijiaoyun-main\main.py", line 176, in topicInfo
    listTopicComment = cellInfo(listTopic, token, sleepTime)
  File "C:\Users\yaoyu\Desktop\zhijiaoyun-main\main.py", line 209, in cellInfo
    cellList = session.post(url, params=params, verify=False).json()['cellList']
  File "C:\Users\yaoyu\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\yaoyu\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\yaoyu\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\yaoyu\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by polaris-stars** [comment]
求解 验证码怎么过的

**Comment by Hawkenm** [comment]
> 求解 验证码怎么过的

就根文件夹下面会出来一个名为：verifycode.png 的文件，打开它就是验证码了

**Comment by Hawkenm** [comment]
#1 问题找到了，解决方法和这个一模一样，也就是等5-10mins

**Comment by Just-to-it** [comment]
> #1 问题找到了，解决方法和这个一模一样，也就是等5-10mins

对的, 这种报错最常见, 就是请求太频繁了。最好等个10分钟。
swf文件等下更新
elif categoryName == '压缩包' or categoryName == 'swf' or categoryName=='链接'  即可

**Comment by Hawkenm** [comment]
> > #1 问题找到了，解决方法和这个一模一样，也就是等5-10mins
> 
> 对的, 这种报错最常见, 就是请求太频繁了。最好等个10分钟。
> swf文件等下更新
> elif categoryName == '压缩包' or categoryName == 'swf' or categoryName=='链接' 即可

老哥稳

**Comment by polaris-stars** [comment]
Traceback (most recent call last):
  File "C:\Users\AW\Downloads\zhijiaoyun-main\zjy.py", line 487, in <module>
    getCookie_acw_tc()
  File "C:\Users\AW\Downloads\zhijiaoyun-main\zjy.py", line 36, in getCookie_acw_tc
    session.get(url, verify=False)
  File "O:\Python\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "O:\Python\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "O:\Python\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "O:\Python\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "O:\Python\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "O:\Python\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "O:\Python\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "O:\Python\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "O:\Python\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "O:\Python\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "O:\Python\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "O:\Python\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

**Comment by Hawkenm** [comment]
> Traceback (most recent call last):
> File "C:\Users\AW\Downloads\zhijiaoyun-main\zjy.py", line 487, in
> getCookie_acw_tc()
> File "C:\Users\AW\Downloads\zhijiaoyun-main\zjy.py", line 36, in getCookie_acw_tc
> session.get(url, verify=False)
> File "O:\Python\lib\site-packages\requests\sessions.py", line 555, in get
> return self.request('GET', url, **kwargs)
> File "O:\Python\lib\site-packages\requests\sessions.py", line 542, in request
> resp = self.send(prep, **send_kwargs)
> File "O:\Python\lib\site-packages\requests\sessions.py", line 655, in send
> r = adapter.send(request, **kwargs)
> File "O:\Python\lib\site-packages\requests\adapters.py", line 439, in send
> resp = conn.urlopen(
> File "O:\Python\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
> self._prepare_proxy(conn)
> File "O:\Python\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
> conn.connect()
> File "O:\Python\lib\site-packages\urllib3\connection.py", line 359, in connect
> conn = self._connect_tls_proxy(hostname, conn)
> File "O:\Python\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy return ssl_wrap_socket( File "O:\Python\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
> ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls) File "O:\Python\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
> return ssl_context.wrap_socket(sock)
> File "O:\Python\lib\ssl.py", line 500, in wrap_socket
> return self.sslsocket_class._create(
> File "O:\Python\lib\ssl.py", line 997, in _create
> raise ValueError("check_hostname requires server_hostname")
> ValueError: check_hostname requires server_hostname

网络问题吧，大兄弟

**Comment by Just-to-it** [comment]
> > Traceback (most recent call last):
> > File "C:\Users\AW\Downloads\zhijiaoyun-main\zjy.py", line 487, in
> > getCookie_acw_tc()
> > File "C:\Users\AW\Downloads\zhijiaoyun-main\zjy.py", line 36, in getCookie_acw_tc
> > session.get(url, verify=False)
> > File "O:\Python\lib\site-packages\requests\sessions.py", line 555, in get
> > return self.request('GET', url, **kwargs)
> > File "O:\Python\lib\site-packages\requests\sessions.py", line 542, in request
> > resp = self.send(prep, **send_kwargs)
> > File "O:\Python\lib\site-packages\requests\sessions.py", line 655, in send
> > r = adapter.send(request, **kwargs)
> > File "O:\Python\lib\site-packages\requests\adapters.py", line 439, in send
> > resp = conn.urlopen(
> > File "O:\Python\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
> > self._prepare_proxy(conn)
> > File "O:\Python\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
> > conn.connect()
> > File "O:\Python\lib\site-packages\urllib3\connection.py", line 359, in connect
> > conn = self._connect_tls_proxy(hostname, conn)
> > File "O:\Python\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy return ssl_wrap_socket( File "O:\Python\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
> > ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls) File "O:\Python\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
> > return ssl_context.wrap_socket(sock)
> > File "O:\Python\lib\ssl.py", line 500, in wrap_socket
> > return self.sslsocket_class._create(
> > File "O:\Python\lib\ssl.py", line 997, in _create
> > raise ValueError("check_hostname requires server_hostname")
> > ValueError: check_hostname requires server_hostname
> 
> 网络问题吧，大兄弟

正解, 网速问题。

**Comment by polaris-stars** [comment]
呜呜呜，看来学校的校园网真差劲呀
